# Generated by Django 5.2 on 2026-04-12 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentists', '0006_remove_customuser_username_and_more'),
        ('patients', '0007_remove_patientprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('patient', 'Patient'), ('dentist', 'Dentist')], max_length=10)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dentists.dentistprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='patients.patientprofile')),
            ],
        ),
    ]
