# Generated by Django 5.2 on 2026-01-29 11:11

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dentists', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='Consultation', max_length=100)),
                ('price_PLN', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purposes', to='dentists.dentistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('start_time', models.TimeField()),
                ('name', models.CharField(default='appointment', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=1800))),
                ('custom_purpose', models.CharField(blank=True, max_length=25)),
                ('status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('passed', 'Passed'), ('completed', 'Completed'), ('did_not_occur', "Didn't Occur"), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('diagnosis', models.CharField(default='No diagnosis yet!', max_length=25)),
                ('description', models.CharField(default='No description yet!', max_length=125)),
                ('converted_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, default='PLN', max_length=3, null=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dentist_site_appointments', to='dentists.dentistprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patientprofile')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointmentpurpose')),
            ],
        ),
    ]
