# Generated by Django 5.2 on 2026-08-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_confirmed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('passed', 'Passed'), ('completed', 'Completed'), ('did_not_occur', "Didn't show up, no notification"), ('cancelled', 'Cancelled')], default='available', max_length=20),
        ),
    ]
