# Generated by Django 5.2 on 2026-01-29 11:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.CharField(choices=[('patient', 'Patient'), ('dentist', 'Dentist'), ('op', 'Op')], default='op', max_length=10)),
                ('username', models.CharField(default='op', max_length=64, null=True, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='dentistProfile',
            fields=[
                ('user_type', models.CharField(choices=[('dentist', 'Dentysta'), ('patient', 'Pacjent')], default='dentist', max_length=10)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, default=str, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, default=str, max_length=254, null=True)),
                ('password', models.CharField(blank=True, default=str, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, default=str, null=True, upload_to='media/')),
                ('short_intro', models.CharField(blank=True, default='This is a default bio. User has not added a bio yet.', max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('university', models.CharField(blank=True, default=str, max_length=64, null=True)),
                ('docs', models.FileField(blank=True, default=str, null=True, upload_to='documents/')),
                ('function', models.CharField(blank=True, choices=[('dentist', 'Dentist'), ('manager', 'Manager'), ('owner', 'Owner')], default='dentist', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('social_website', models.CharField(blank=True, max_length=2000, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dentistProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='dentists.dentistprofile')),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='DentistSchedule',
            fields=[
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dentists.dentistprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('vote_total', models.IntegerField(blank=True, default=0, null=True)),
                ('vote_ratio', models.IntegerField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentists.dentistprofile')),
            ],
        ),
        migrations.AddField(
            model_name='dentistprofile',
            name='particip_project',
            field=models.ManyToManyField(blank=True, to='dentists.project'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('body', models.TextField(blank=True, null=True)),
                ('value', models.CharField(choices=[('up', 'Up Vote'), ('down', 'Down Vote')], max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentists.dentistprofile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dentists.project')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('skill_image', models.ImageField(blank=True, default=str, null=True, upload_to='media/')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentists.dentistprofile')),
                ('tags', models.ManyToManyField(blank=True, to='dentists.tag')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='skill_used',
            field=models.ManyToManyField(blank=True, to='dentists.skill'),
        ),
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dentists.dentistprofile')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='dentists.tag'),
        ),
    ]
