# Generated by Django 5.2 on 2026-02-01 14:12

import dentists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pesel',
            field=models.CharField(default=66666666666, max_length=11, unique=True,),
            preserve_default=False,
        ),
    ]
