# Generated by Django 5.2 on 2026-02-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0002_customuser_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pesel',
        ),
    ]
