# Generated by Django 5.2 on 2026-02-01 14:27

import dentists.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0003_remove_customuser_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pesel',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True,),
        ),
    ]
