# Generated by Django 5.2 on 2026-03-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0004_customuser_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentistprofile',
            name='username',
        ),
    ]
