# Generated by Django 5.2 on 2026-03-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0005_remove_dentistprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='dentistprofile',
            name='email',
        ),
    ]
