# Generated by Django 5.2 on 2026-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0006_remove_customuser_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='function',
            field=models.CharField(blank=True, choices=[('dentist', 'Dentist'), ('manager', 'Manager'), ('owner', 'Owner')], default='dentist', max_length=200, null=True),
        ),
    ]
