# Generated by Django 5.2 on 2026-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0007_alter_dentistprofile_function'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='photo',
            field=models.ImageField(blank=True, default=str, null=True, upload_to=''),
        ),
    ]
