# Generated by Django 5.2 on 2026-04-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0008_alter_dentistprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, default=str, null=True, upload_to=''),
        ),
    ]
