# Generated by Django 5.2 on 2026-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0009_alter_project_project_image_alter_skill_skill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='photo',
            field=models.ImageField(blank=True, default=str, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, default=str, null=True, upload_to='media/'),
        ),
    ]
