# Generated by Django 5.2 on 2026-04-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0010_alter_dentistprofile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='photo',
            field=models.ImageField(blank=True, default=str, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_image',
            field=models.ImageField(blank=True, default=str, null=True, upload_to='skills/'),
        ),
    ]
