# Generated by Django 5.2 on 2026-06-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0012_project_demo_link_project_source_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentistprofile',
            name='short_intro',
            field=models.CharField(blank=True, default='Dentist', max_length=200, null=True),
        ),
    ]
