# Generated by Django 5.2 on 2026-08-19 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0013_alter_dentistprofile_short_intro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
