# Generated by Django 5.2 on 2026-01-29 11:10

import django.db.models.deletion
import patients.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('user_type', models.CharField(choices=[('dentist', 'Dentysta'), ('patient', 'Pacjent')], default='patient', max_length=10)),
                ('username', models.CharField(default=str, max_length=64, null=True, unique=True)),
                ('email', models.EmailField(default=str, max_length=254, null=True)),
                ('password', models.CharField(default=str, max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('pesel', models.CharField(max_length=11, unique=True,)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, default=str, null=True, upload_to='media/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patientProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=patients.models.document_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patientprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patientprofile')),
            ],
        ),
    ]
