# Generated by Django 5.2 on 2026-02-01 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='pesel',
        ),
    ]
