# Generated by Django 5.2 on 2026-02-01 14:14

import patients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patientprofile_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='pesel',
            field=models.CharField(default=44444444444, max_length=11, unique=True, ),
            preserve_default=False,
        ),
    ]
