# Generated by Django 5.2 on 2026-02-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patientprofile_pesel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='pesel',
        ),
    ]
