# Generated by Django 5.2 on 2026-02-01 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0004_customuser_pesel'),
        ('patients', '0004_remove_patientprofile_pesel'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='linked_dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dentists.dentistprofile'),
        ),
    ]
