# Generated by Django 5.2 on 2026-03-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patientprofile_linked_dentist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='username',
        ),
    ]
