# Generated by Django 5.2 on 2026-03-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patientprofile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='email',
        ),
    ]
