# Generated by Django 5.2 on 2026-04-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_patientprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='photo',
            field=models.ImageField(blank=True, default=str, null=True, upload_to=''),
        ),
    ]
