# Generated by Django 5.2 on 2026-04-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_alter_patientprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='photo',
            field=models.ImageField(blank=True, default=str, null=True, upload_to='media/'),
        ),
    ]
