# Generated by Django 5.2 on 2026-05-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentists', '0011_alter_dentistprofile_photo_and_more'),
        ('patients', '0009_alter_patientprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='linked_dentist',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='linked_dentists',
            field=models.ManyToManyField(blank=True, related_name='linked_patients', to='dentists.dentistprofile'),
        ),
    ]
